kind: pipeline
name: docker

trigger:
  branch:
    - dev

platform:
  runner: 10.11.92.40

workspace:
  path: github.com/tmate-io/tmate

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: docker-builder-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-amd64
      dockerfile: .beagle/builder/dockerfile
      repo: wod-arm/tmate-builder
      version: alpine-3.14
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-builder-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-arm64
      dockerfile: .beagle/builder/dockerfile
      repo: wod-arm/tmate-builder
      version: alpine-3.14
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-builder-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-ppc64le
      dockerfile: .beagle/builder/dockerfile
      repo: wod-arm/tmate-builder
      version: alpine-3.14
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-builder-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.11-mips64le
      dockerfile: .beagle/builder/dockerfile
      repo: wod-arm/tmate-builder
      version: alpine-3.11
      channel: mips64le
      args: 'TARGETOS=linux,TARGETARCH=mips64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - master

platform:
  runner: 10.11.92.40

workspace:
  path: github.com/tmate-io/tmate

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: builder-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate-builder:alpine-3.14-amd64
    commands:
      - ./autogen.sh && ./configure --enable-static
      - make -j $(nproc)
      - objcopy --only-keep-debug tmate tmate.symbols && strip tmate
      - ./tmate -V
      - mkdir -p release/linux/amd64/
      - mv tmate release/linux/amd64/tmate

  - name: builder-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate-builder:alpine-3.14-arm64
    commands:
      - ./autogen.sh && ./configure --enable-static
      - make -j $(nproc)
      - objcopy --only-keep-debug tmate tmate.symbols && strip tmate
      - ./tmate -V
      - mkdir -p release/linux/arm64/
      - mv tmate release/linux/arm64/tmate

  - name: builder-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate-builder:alpine-3.14-ppc64le
    commands:
      - ./autogen.sh && ./configure --enable-static
      - make -j $(nproc)
      - objcopy --only-keep-debug tmate tmate.symbols && strip tmate
      - ./tmate -V
      - mkdir -p release/linux/ppc64le/
      - mv tmate release/linux/ppc64le/tmate

  - name: builder-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate-builder:alpine-3.11-mips64le
    commands:
      - ./autogen.sh && ./configure --enable-static
      - make -j $(nproc)
      - objcopy --only-keep-debug tmate tmate.symbols && strip tmate
      - ./tmate -V
      - mkdir -p release/linux/mips64le/
      - mv tmate release/linux/mips64le/tmate

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-amd64
      dockerfile: .beagle/dockerfile
      repo: wod-arm/tmate
      version: 2.4.0
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-arm64
      dockerfile: .beagle/dockerfile
      repo: wod-arm/tmate
      version: 2.4.0
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-ppc64le
      dockerfile: .beagle/dockerfile
      repo: wod-arm/tmate
      version: 2.4.0
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.11-mips64le
      dockerfile: .beagle/dockerfile
      repo: wod-arm/tmate
      version: 2.4.0
      channel: mips64le
      args: 'TARGETOS=linux,TARGETARCH=mips64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/mips64le
      template: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod-arm/tmate:2.4.0
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: USERNAME
  path: devops-registry-aliyun

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: PASSWORD
  path: devops-registry-aliyun
