name: NetBSD
on:
  push:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/NetBSD.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/NetBSD.yml'



jobs:
  NetBSD:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: vmactions/netbsd-vm@v0
      with:
        prepare: |
          pkg_add  automake autoconf libtool pkgconf libevent msgpack libssh
        usesh: true
        run: |
          autoupdate
          ./autogen.sh
          ./configure
          make
          make install



