name: OpenBSD
on:
  push:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/OpenBSD.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - '.github/workflows/OpenBSD.yml'



jobs:
  OpenBSD:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: vmactions/openbsd-vm@v0
      with:
        prepare: |
          pkg_add  automake-1.16.3  autoconf-2.71  libtool pkgconf libevent msgpack libssh curl
        usesh: true
        run: |
          sed -i 's,<event.h>,<event2/event.h>,'  *.[ch]
          curl https://raw.githubusercontent.com/openbsd/ports/master/sysutils/tmate/patches/patch-Makefile_am       | patch
          curl https://raw.githubusercontent.com/openbsd/ports/master/sysutils/tmate/patches/patch-server_c          | patch
          curl https://raw.githubusercontent.com/openbsd/ports/master/sysutils/tmate/patches/patch-tmate-debug_c     | patch
          curl https://raw.githubusercontent.com/openbsd/ports/master/sysutils/tmate/patches/patch-tmate_h           | patch
          curl https://raw.githubusercontent.com/openbsd/ports/master/sysutils/tmate/patches/patch-tmux_c            | patch
          curl https://raw.githubusercontent.com/openbsd/ports/master/sysutils/tmate/patches/patch-tmux_h            | patch
          curl https://raw.githubusercontent.com/openbsd/ports/master/sysutils/tmate/patches/patch-osdep-openbsd_c   | patch
          export AUTOMAKE_VERSION=1.16
          export AUTOCONF_VERSION=2.71
          autoupdate
          ./autogen.sh
          ./configure
          make
          make install



